### ISSUE TITLE
Ability to delete/rechain a chain

### ISSUE THREAD

**Issue by axelerator** [Shopify/git-chain#2]
I have successfully setup and used my chain i.e.:

`master -> A ->B ->C`

Scenario:
My PR was approved and merged! So now I would like to adapt my chain to be:

`master -> B ->C`

The way I did it now was to remove the chain manually and then setting it up again.
For that I have to edit the git config manually which is errorprone and cumbersome.

It would be nice to have a command to delete or alter existing chains :-)

**Comment by mzhu25** [comment]
Related to this, I tried updating the chain by simply using `git chain setup` to overwrite the existing chain, but ran into some unexpected behavior:
```
Michaels-MacBook-Pro:monorepo michaelzhu$ git chain list
  current [development -> feature/forwarder/erc20-bridge-buy -> refactor/integrations/transaction-tests -> feature/forwarder/recipient-address]
* fuzz [development -> feature/fuzz/makers-and-takers -> feature/fuzz/prng -> feature/fuzz/staking-rewards]
Michaels-MacBook-Pro:monorepo michaelzhu$ git chain setup -c fuzz feature/fuzz/makers-and-takers feature/fuzz/prng feature/fuzz/staking-rewards
Removed development from the chain.
✓ Configured chain fuzz [feature/fuzz/makers-and-takers -> feature/fuzz/prng -> feature/fuzz/staking-rewards]
Michaels-MacBook-Pro:monorepo michaelzhu$ git chain list
  current [development -> feature/forwarder/erc20-bridge-buy -> refactor/integrations/transaction-tests -> feature/forwarder/recipient-address]
* fuzz [development -> feature/fuzz/makers-and-takers -> feature/fuzz/prng -> feature/fuzz/staking-rewards]
```
It says "Removed development from the chain" but the following `git chain list` would suggest that `development` is still in the chain. Unclear if the chain was actually updated or not.

**Comment by Blackhex** [comment]
I please for this and I'd also appreciate an ability to add an existing branch (e.g. created from Jira) to the chain.

**Comment by zenspider** [comment]
I could have sworn I just did this... 2 of my stack were merged (from the bottom) and then I re-ran `setup` with the two removed and watched it rewrite the branch configs affected.

**Comment by zenspider** [comment]
Confirmed as fixed: I do this all the time.

**Comment by arcticlinux** [comment]
It was entirely unclear how to delete/manually edit even after skimming this issue, but editing `.git/config` and removing `chain =`, `parentBranch =`, and `branchPoint =` entries does the trick.
